apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arc-runner-role
  namespace: arc-runners # Ensure this matches your runner namespace
rules:
- apiGroups: [""] # Core API group
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get", "create"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "delete", "get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arc-runner-rolebinding
  namespace: arc-runners # Ensure this matches your runner namespace
subjects:
- kind: ServiceAccount
  name: arc-runner-serviceaccount # Replace with your service account name
  namespace: arc-runners # Ensure this matches your runner namespace
roleRef:
  kind: Role
  name: arc-runner-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arc-runner-serviceaccount # Replace with your service account name
  namespace: arc-runners # Ensure this matches your runner namespace