name: Terraform Runner Setup

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose Terraform action"
        required: true
        type: choice
        options:
          - apply
          - destroy
    #   git_token:
    #     description: "GitHub Runner Auth Token"
    #     required: true
    #   runner_version:
    #     description: "Specify the runner version"
    #     required: true
    #     default: "2.284.0"
    #   repo_url:
    #     description: "Specify the repository URL"
    #     required: true

env:
  USERNAME: "kapil987"
  REPOSITORY: "articles"
  RUNNER_NAME: "my-demo-runner"
  REPO_URL: "https://github.com/Kapil987/articles"
  RUNNER_VERSION: "2.320.0"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: true
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: View checkout repo contents
      run: ls -la && pwd
    
    - name: Authenticate to GitHub
      run: |
        echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

    - name: Generate Runner Token
      id: generate_token
      run: |
        RUNNER_TOKEN=$(gh api \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          /repos/$USERNAME/$REPOSITORY/actions/runners/registration-token \
          | jq -r '.token')
        echo "RUNNER_TOKEN=$RUNNER_TOKEN" >> $GITHUB_ENV
        
    - name: Terraform Apply or Destroy
      run: |
        cd terraform-files
        terraform init
        terraform ${{ github.event.inputs.action }} -auto-approve -var git_token=${{ env.RUNNER_TOKEN }} -var repo_url=${{ env.REPO_URL }} -var runner_name=${{ env.RUNNER_NAME }}