name: CICD for Dockerized Flask APP

# Trigger the workflow on Events: any push to the main branch or pull request
on:
  # workflow_dispatch:  # Only manual triggers either this line or below line

  # Automatic trigger start
  push: # an event
    branches: [main]
  pull_request:
    branches: [main]

  # Automatic trigger end

jobs:
  setup-env--and-test:
    runs-on: ubuntu-latest # containers
    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v4 # git clone

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Installing dependencies
        working-directory: ./2.python-flask-app
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Step 4: Run tests
      - name: Run tests
        run: pytest # runs file which start with test_

  build-and-publish:
    needs: setup-env--and-test # setting dependency
    runs-on: ubuntu-latest # containers
    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v4 # git clone

      - name: set up Docker buildx
        uses: docker/setup-buildx-actions@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} # repository secret
          
          # https://github.com/docker/build-push-action
      - name: Build and push
        id: build-and-publish
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/flask-you-may-delete-app:latest
      
      # ref https://github.com/docker/build-push-action
      - name: Image digest
        run: echo ${{ steps.build-and-publish.outputs.digest}}