name: Test Docker on GitHub Actions

on:
  workflow_dispatch: 

jobs:
  push_container:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y docker.io

      - name: Test Docker
        run: |
          docker version
          docker info
      - name: Build and push Docker image with Kaniko
        uses: int128/kaniko-action@v1
        with:
          context: ./2.python-flask-app # Path to your app's directory (containing Dockerfile)
          file: Dockerfile # Path to your app's Dockerfile
          tags: your-dockerhub-username/your-image-name:latest # Replace with your info
          # push: true # Only include if you want to push to a registry. Remove for local build.
          # cache: true # Optional
          # cache-repository: ghcr.io/${{ github.repository }}/cache # Optional