name: Build and Push Docker Image using Kaniko

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: gha-runner-scale-set
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Docker Metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          # Replace "my-app" with your repository/image name
          images: ${{ vars.DOCKERHUB_USERNAME }}/my-app

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: docker.io

      - name: Build and Push Image using Kaniko
        uses: int128/kaniko-action@v1
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache: true
          # Optionally set a cache repository (update "my-app-cache" as needed)
          cache-repository: ${{ vars.DOCKERHUB_USERNAME }}/my-app-cache
