name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set # This assumes your ARC runner environment has Docker installed/available
    steps:
    - name: Display Initial Message
      run: echo "🎉 This job uses runner scale set runners!"

    - name: Check Docker Version
      run: docker --version # Add this step to run the command