name: Kaniko demo2
on:
  workflow_dispatch:

jobs:
  build:
    # This job will now run on your ARC runner scale set
    # runs-on: [arc-runner-set]
    runs-on: [arc-runner-set]
    container:
      image: gcr.io/kaniko-project/executor:debug
    permissions:
      contents: read     # Needed for checkout
      packages: write    # Needed if you push to a registry
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # - name: Set up Docker Authentication for Docker Hub
      #   run: |
      #     mkdir -p /kaniko/.docker
      #     echo "{\"auths\": {\"https://index.docker.io/v1/\": {\"username\": \"${{ secrets.DOCKERHUB_USERNAME }}\", \"password\": \"${{ secrets.DOCKERHUB_PASSWORD }}\"}}}" > /kaniko/.docker/config.json

      # - name: Build and Push Image to Docker Hub
      #   run: |
      #     IMAGE_NAME=your-dockerhub-username/your-image-name
      #     TAG=latest
      #     /kaniko/executor \
      #       --dockerfile=Dockerfile \
      #       --context=$(pwd) \
      #       --destination=${IMAGE_NAME}:${TAG} \
      #       --no-push=false