name: Kaniko demo2
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [arc-runner-set]
    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v4 # git clone

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Installing dependencies
        working-directory: ./2.python-flask-app
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Step 4: Run tests
      - name: Run tests
        run: pytest # runs file which start with test_
